# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';
in
linkFarm name [
  {
    name = "godot_zig-0.0.0-5_wrXkmRRAAZPHv-fCt8NRVke0GHsZd6xm_WoFKw2jSI.tar.gz";
    path = fetchZig {
      name = "godot_zig";
      url = "git+https://github.com/f3lixding/godot-zig?ref=main#c85b308ba358a4046a4ffa29b312e93eb67b3546";
      hash = "sha256-iCYgFzPco741QgHiOPdPVrbM6tfqiWR5WUdkfzMZCWM=";
    };
  }
]
