# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';
in
linkFarm name [
  {
    name = "godot_zig-0.0.0-5_wrXhzIQgCOpKAYTltdrqnF6gmxRKGSmRYUB-TRl7EC.tar.gz";
    path = fetchZig {
      name = "godot_zig";
      url = "git+https://github.com/f3lixding/godot-zig?ref=main#5c2bfae82c0d1c10b57d24d4f39c8ea4d5beb141";
      hash = "sha256-o2HlayYrrvwVdIfFsrLpZSBf19u2Al7KRR0YMH8/tCw=";
    };
  }
]
