# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';
in
linkFarm name [
  {
    name = "godot_zig-0.0.0-5_wrXp5iQwBegN0tyEfCDIp0ucRnhQbVkPowRvrhNzic.tar.gz";
    path = fetchZig {
      name = "godot_zig";
      url = "git+https://github.com/f3lixding/godot-zig?ref=main#3d6a434c8e37f84d7c9b22ca1f1f0e9a4a599c25";
      hash = "sha256-TdbjYYUmLBGnkHm4ikjUj0VnxfSNWxA6lhSgvdfL278=";
    };
  }
]
